anguage: shell

install:
 - sudo service postgresql stop
 - sudo apt-get update
 - ls /etc/postgresql
 - pg_config --version
 - sudo apt-get -y install postgresql-server-dev-all postgis
 - sudo apt-get -y install curl sudo make build-essential g++ python-logilab-common python3-pip
 - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
 - sudo apt-get install -y nodejs
 - echo "listen_addresses = '*'" >> sudo /etc/postgresql/10.1/main/postgresql.conf
 - sudo service postgresql restart
 - sudo -i -u postgres psql -c "CREATE USER test with password 'test'"
 - sudo -i -u postgres psql -c "CREATE USER admin_test with password 'admin_test'"
 - sudo -i -u postgres psql -c "CREATE DATABASE cacophonytest WITH OWNER test;"
 - sudo -i -u postgres psql cacophonytest -c "CREATE EXTENSION postgis"
 - cp config/app_test_TEMPLATE.js config/app.js
 - npm install
 - node_modules/sequelize-cli/bin/sequelize db:migrate --config config/app.js
 - wget https://dl.minio.io/server/minio/release/linux-amd64/minio
 - chmod +x minio
 - wget https://dl.minio.io/client/mc/release/linux-amd64/mc
 - chmod +x mc
 - sudo -i -u postgres psql cacophonytest -f "test/db-seed.sql"
 - MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=miniostorage ./minio server --address :9001 .data &> miniolog &
 - sleep 10
 - ./mc config host add myminio http://127.0.0.1:9001 minio miniostorage
 - ./mc mb myminio/cacophony
 - node Server.js &
script:
 - cd test 
 - sudo pip3 install virtualenv
 - virtualenv env && source env/bin/activate
 - pip3 install -r requirements.txt
 - pytest -s  