language: shell

sudo: required

services:
  - docker
  
install:
 - ./docker-start.sh
 
script:
 - cd test 
 - sudo pip3 install virtualenv
 - virtualenv env && source env/bin/activate
 - sudo pip3 install -r requirements.txt
 - pytest -s 
  