sudo: required

services:
  - docker
  
dist: trusty

language: python
python:
  - "3.6"
  
install:
 - ./docker-start.sh &

script:
 - cd test 
 - pip install virtualenv
 - virtualenv env && source env/bin/activate
 - pip install -r requirements.txt
 - pytest -s  